apiVersion: apps/v1
kind: Deployment
metadata:
  name: strokee-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strokee-nginx
  template:
    metadata:
      labels:
        app: strokee-nginx
    spec:
      containers:
        - name: strokee-nginx
          image: nginx:latest
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
            - name: nginx-ssl
              mountPath: /etc/nginx/ssl
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: nginx-ssl
          secret:
            secretName: strokee-tls-secret
---
apiVersion: v1
kind: Service
metadata:
  name: strokee-nginx
spec:
  type: NodePort
  selector:
    app: strokee-nginx
  ports:
    - name: http  # Add a name for the HTTP port
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # External port for HTTP
    - name: https  # Add a name for the HTTPS port
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30443  # External port for HTTPS
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strokee-system-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strokee-system-api
  template:
    metadata:
      labels:
        app: strokee-system-api
    spec:
      containers:
        - name: strokee-system-api
          image: carlos29ac/strokee-api-service:latest
          envFrom:
              - secretRef:
                  name: app-secrets  # Secret para variables sensibles
          ports:
            - containerPort: 4001
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 1.1.1.1
---
apiVersion: v1
kind: Service
metadata:
  name: strokee-system-api-service
spec:
  type: NodePort
  selector:
    app: strokee-system-api
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
      nodePort: 30001  # External port for API
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strokee-notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strokee-notification-service
  template:
    metadata:
      labels:
        app: strokee-notification-service
    spec:
      containers:
        - name: strokee-notification-service
          image: carlos29ac/strokee-notification-service:latest
          envFrom:
              - secretRef:
                  name: app-secrets  # Secret para variables sensibles
          ports:
            - containerPort: 4002
---
apiVersion: v1
kind: Service
metadata:
  name: strokee-notification-service
spec:
  type: NodePort
  selector:
    app: strokee-notification-service
  ports:
    - protocol: TCP
      port: 4002
      targetPort: 4002
      nodePort: 30002  # External port for Notification Service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-strokee-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-strokee-system
  template:
    metadata:
      labels:
        app: mongo-strokee-system
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          command: ["/bin/sh", "-c", "mongod --replSet rs0 --bind_ip_all & sleep 5 && mongosh --eval 'rs.initiate({_id: \"rs0\", members: [{ _id: 0, host: \"mongo-strokee-system:27017\" }]})' && wait"]
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-strokee-system
spec:
  type: NodePort  # Cambia a NodePort
  selector:
    app: mongo-strokee-system
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30017  # Puerto accesible externamente
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-strokee-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-strokee-system
  template:
    metadata:
      labels:
        app: rabbitmq-strokee-system
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-strokee-system
spec:
  selector:
    app: rabbitmq-strokee-system
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672