version: '3.8'

services:

  strokee-nginx:
    image: nginx:latest
    container_name: strokee-nginx
    restart: always
    depends_on:
      - strokee-system-api-service
      - strokee-notification-service
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/strokee.conf:/etc/nginx/conf.d/strokee.conf
      - ./nginx/ssl:/etc/nginx/ssl
    networks:
      - strokee_network

  strokee-system-api-service:
    image: carlos29ac/strokee-api-service:latest
    env_file:
      - .env
    container_name: strokee-system-api-service
    restart: always
    depends_on:
      mongo-strokee-system:
        condition: service_healthy
      rabbitmq-strokee-system:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - strokee_network
  
  strokee-notification-service:
    image: carlos29ac/strokee-notification-service:latest
    env_file:
      - .env
    container_name: strokee-notification-service
    restart: always
    depends_on:
      mongo-strokee-system:
        condition: service_started
      rabbitmq-strokee-system:
        condition: service_healthy
    networks:
      - strokee_network

  mongo-strokee-system:
    image: mongo:latest
    container_name: mongo-strokee-system
    restart: always
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    command: mongod --bind_ip_all --auth
    ports:
      - "27017"
    volumes:
      - mongo_data:/data/db
      - ./database/mongo.conf:/etc/mongo.conf
    networks:
      - strokee_network
    healthcheck:
      test: >
        echo 'db.runCommand({usersInfo: {user: \"$$MONGO_INITDB_ROOT_USERNAME\", db: \"admin\"}})' | 
        mongosh --username $$MONGO_INITDB_ROOT_USERNAME --password $$MONGO_INITDB_ROOT_PASSWORD --quiet
      interval: 10s
      retries: 5
      start_period: 10s

  rabbitmq-strokee-system:
    image: rabbitmq:3-management
    container_name: rabbitmq-strokee-system
    restart: always
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - "15672"
    networks:
      - strokee_network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5

networks:
  strokee_network:
    driver: bridge

volumes:
  mongo_data: