openapi: 3.0.0
info:
  title: API de Registro de Pacientes
  description: API para registrar pacientes en el sistema.
  version: 1.0.0
paths:
  /patients/register:
    post:
      summary: Registrar un nuevo paciente
      description: Registra un nuevo paciente proporcionando detalles personales e información médica.
      operationId: registerPatient
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                  example: 'John'
                  description: El primer nombre del paciente.
                lastName:
                  type: string
                  example: 'Doe'
                  description: El apellido del paciente.
                email:
                  type: string
                  example: 'johndoe@example.com'
                  description: La dirección de correo electrónico del paciente.
                password:
                  type: string
                  example: 'password123'
                  description: La contraseña para el paciente.
                phoneNumber:
                  type: string
                  example: '1234567890'
                  description: El número de teléfono del paciente.
                age:
                  type: integer
                  example: 30
                  description: La edad del paciente.
                birthDate:
                  type: string
                  format: date
                  example: '1995-01-01'
                  description: La fecha de nacimiento del paciente.
                weight:
                  type: number
                  format: float
                  example: 70
                  description: El peso del paciente en kilogramos.
                height:
                  type: number
                  format: float
                  example: 175
                  description: La altura del paciente en centímetros.
                medications:
                  type: array
                  items:
                    type: string
                  example: ['med1']
                  description: Lista de los medicamentos actuales del paciente.
                conditions:
                  type: array
                  items:
                    type: string
                  example: ['condition1']
                  description: Lista de las condiciones médicas preexistentes del paciente.
      responses:
        '201':
          description: Paciente registrado exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Paciente agregado exitosamente.'
                  patientId:
                    type: string
                    example: '12345'
        '400':
          description: Solicitud incorrecta, el registro falló.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'El email ya está registrado.'
        '500':
          description: Error interno del servidor.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: 'Error desconocido al agregar al paciente.'
