apiVersion: apps/v1
kind: Deployment
metadata:
  name: strokee-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strokee-nginx
  template:
    metadata:
      labels:
        app: strokee-nginx
    spec:
      containers:
        - name: strokee-nginx
          image: nginx:latest
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
            - name: nginx-ssl
              mountPath: /etc/nginx/ssl
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: nginx-ssl
          secret:
            secretName: strokee-tls-secret
---
apiVersion: v1
kind: Service
metadata:
  name: strokee-nginx
spec:
  type: NodePort
  selector:
    app: strokee-nginx
  ports:
    - name: http  # Add a name for the HTTP port
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # External port for HTTP
    - name: https  # Add a name for the HTTPS port
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30443  # External port for HTTPS
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strokee-system-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strokee-system-api
  template:
    metadata:
      labels:
        app: strokee-system-api
    spec:
      containers:
        - name: strokee-system-api
          image: carlos29ac/strokee-api-service:latest
          envFrom:
              - secretRef:
                  name: app-secrets  # Secret para variables sensibles
          ports:
            - containerPort: 4001
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 1.1.1.1
---
apiVersion: v1
kind: Service
metadata:
  name: strokee-system-api-service
spec:
  selector:
    app: strokee-system-api
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strokee-notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strokee-notification-service
  template:
    metadata:
      labels:
        app: strokee-notification-service
    spec:
      containers:
        - name: strokee-notification-service
          image: carlos29ac/strokee-notification-service:latest
          envFrom:
              - secretRef:
                  name: app-secrets  # Secret para variables sensibles
          ports:
            - containerPort: 4002
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 1.1.1.1
---
apiVersion: v1
kind: Service
metadata:
  name: strokee-notification-service
spec:
  selector:
    app: strokee-notification-service
  ports:
    - protocol: TCP
      port: 4002
      targetPort: 4002
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mongo"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-strokee-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-strokee-system
  template:
    metadata:
      labels:
        app: mongo-strokee-system
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MONGO_INITDB_ROOT_PASSWORD
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-strokee-system
spec:
  type: ClusterIP
  selector:
    app: mongo-strokee-system
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-strokee-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-strokee-system
  template:
    metadata:
      labels:
        app: rabbitmq-strokee-system
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_DEFAULT_PASS
          ports:
            - containerPort: 5672  # AMQP
            - containerPort: 15672  # Management UI
          readinessProbe:
            exec:
              command:
                - rabbitmqctl
                - status
            initialDelaySeconds: 20
            periodSeconds: 60
            timeoutSeconds: 10
          livenessProbe:
            exec:
              command:
                - rabbitmqctl
                - status
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-strokee-system
spec:
  selector:
    app: rabbitmq-strokee-system
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-strokee-system-management
spec:
  type: NodePort  
  selector:
    app: rabbitmq-strokee-system 
  ports:
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 31672 
