paths:
  /login:
    post:
      summary: Iniciar sesión de un usuario
      description: Autentica a un usuario utilizando un token y configura una cookie de sesión.
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - token
              properties:
                token:
                  type: string
                  example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
      responses:
        200:
          description: Login exitoso.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Login exitoso."
                  userId:
                    type: string
                    example: "user-id-12345"
        400:
          description: Token no válido o vacío.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Token no valido o vacío."
        401:
          description: Token inválido.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Token inválido"
        404:
          description: Usuario no encontrado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Usuario no encontrado."
        500:
          description: Error interno en el servidor.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Error al loguear usuario."
                  error:
                    type: string
                    example: "Error desconocido."

  /logout:
    post:
      summary: Cerrar sesión de un usuario
      description: Borra la cookie de sesión del usuario y finaliza la sesión.
      tags:
        - Auth
      responses:
        200:
          description: Desconexión exitosa.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Desconectado correctamente."
